# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\chatwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(250, 71)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image = QtWidgets.QLabel(Form)
        self.image.setObjectName("image")
        self.horizontalLayout.addWidget(self.image)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.name = QtWidgets.QLabel(Form)
        self.name.setObjectName("name")
        self.horizontalLayout_8.addWidget(self.name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.time = QtWidgets.QLabel(Form)
        self.time.setObjectName("time")
        self.horizontalLayout_8.addWidget(self.time)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.text = QtWidgets.QLabel(Form)
        self.text.setObjectName("text")
        self.horizontalLayout_9.addWidget(self.text)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.unread = QtWidgets.QLabel(Form)
        self.unread.setObjectName("unread")
        self.horizontalLayout_9.addWidget(self.unread)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.image.setText(_translate("Form", "avatar"))
        self.name.setText(_translate("Form", "name"))
        self.time.setText(_translate("Form", "time"))
        self.text.setText(_translate("Form", "name: text"))
        self.unread.setText(_translate("Form", "unread"))
